### PR TITLE
Use provided scope for Flow deps

### PR DESCRIPTION
**Pull request by denis-anisimov**
Part of #3630

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button-flow/55)

### CODE REVIEW

**Comment by ZheSun88** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-button-flow/55#-LBtHPATCsUE6pwu67bN:-LBtHPATCsUE6pwu67bO:b-6vhka6) (no related file):*
Is it possible to move the new profile to `flow-component-base` project? then i think it will lighter the pom for every component and , possibly, don't need to change the running configure for CI and develop usage.. 

https://github.com/vaadin/flow-component-base/blob/master/pom.xml#L267

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button-flow/55)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-button-flow/55#-LBtHPATCsUE6pwu67bN:-LBtIlMRB1IMVGDJbetA:b-vqs1t3) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Is it possible to move the new profile to `flow-component-base` project? then i think it will lighter the pom for every component and , possibly, don't need to change the running configure for CI and develop usage.. 

https://github.com/vaadin/flow-component-base/blob/master/pom.xml#L267
</blockquote></details>

CI has to be changed anyway. I don't see how moving profile to the parent project makes build working without any change.
In fact the build config is already changed to make components running tests.

Various components have various dependencies. So the profile is technically different per component.
But it might be that it's not important for the tests where more dependencies are not a problem.
I will see. May be it has sense to move this profile to the parent if it works.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button-flow/55)*

**Comment by ZheSun88** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-button-flow/55#-LBtHPATCsUE6pwu67bN:-LBtJzl_52rVfdoD3MNw:bpc0ujw) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

CI has to be changed anyway. I don't see how moving profile to the parent project makes build working without any change.
In fact the build config is already changed to make components running tests.

Various components have various dependencies. So the profile is technically different per component.
But it might be that it's not important for the tests where more dependencies are not a problem.
I will see. May be it has sense to move this profile to the parent if it works.
</blockquote></details>

In the parent POM, we have a profile which is active by default. I am thinking, if we move the common part there, then we don't need to run `mvn install -PrunTests` for testing purpose. But yeah, it looks different compnents has different needs on the dependency, so that would be a problem. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button-flow/55)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-button-flow/55#-LBtHPATCsUE6pwu67bN:-LBtOuUqA9eFK7Awl_o5:bwlt38s) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

In the parent POM, we have a profile which is active by default. I am thinking, if we move the common part there, then we don't need to run `mvn install -PrunTests` for testing purpose. But yeah, it looks different compnents has different needs on the dependency, so that would be a problem. 
</blockquote></details>

The whole idea of those PRs is to avoid running by default something. Here it's dependencies that should have `compile ` scope only when tests are executed and not by default.
So there should be a separate profile which is not active by default and used only to run tests.

But anyway. Test deps within the tests profile may be extracted to the parent I think.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button-flow/55)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-button-flow/55#-LBtHPATCsUE6pwu67bN:-LBtQmp29sOR2KZJpqjv:b-3inutw) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

The whole idea of those PRs is to avoid running by default something. Here it's dependencies that should have `compile ` scope only when tests are executed and not by default.
So there should be a separate profile which is not active by default and used only to run tests.

But anyway. Test deps within the tests profile may be extracted to the parent I think.
</blockquote></details>

Profile is extracted to the base project : https://github.com/vaadin/flow-component-base/pull/49

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button-flow/55)*

**Comment by ZheSun88** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/vaadin/vaadin-button-flow/55#-LBtHPATCsUE6pwu67bN:-LBtQe6h4jZ8IzT_63Qm:b-7spegr) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Profile is extracted to the base project : https://github.com/vaadin/flow-component-base/pull/49
</blockquote></details>

Oh i see.. Thanks for clarifying this to me. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button-flow/55)*

**Comment by ZheSun88** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button-flow/55#-:-LBtxA2ICAeB1K-YKucr:bnfp4nl)*

**Pull request merged**
