### PR TITLE
Apply hasEnabled interface to the component

### LINKED ISSUE #47: Clicking on disabled button in test triggers click event
It seems like TestBench does not respect buttons being disabled. If you add a disabled button with a click listener, and execute button.click() in TestBench, the click event will still fire.

See [this commit](https://github.com/brp-olle/vaadin-button-flow/commit/92fc525b2508a20691b01dd50bef55e68b9c2476), which causes the test to fail

### PR DESCRIPTION
**Pull request by ZheSun88**
Add a unit test for that

Fixes #47 

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button-flow/50)

### CODE REVIEW

**Comment by gilberto-torrezan** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/50#-L9iH4q7AAAjpMEsn2qe:-L9iH4q7AAAjpMEsn2qf:b-65zbcr) (no related file):*
The demo for the feature is missing.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/50)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/50#-L9iH4q7AAAjpMEsn2qe:-L9iTHEE-fNQY1gNIqaT:b-2c7ync) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

The demo for the feature is missing.
</blockquote></details>

actually, we have had a demo for disable button already, https://github.com/vaadin/vaadin-button-flow/blob/master/src/test/java/com/vaadin/flow/component/button/demo/ButtonView.java#L133.. but now the problem is how to implement the method itself..:-(

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/50)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/50#-L9iH4q7AAAjpMEsn2qe:-L9ieFve23MJ3rufRPuJ:b4oarij) (no related file):*
<details><summary><i>Previously, gilberto-torrezan (Gilberto Torrezan) wrote…</i></summary><blockquote>

Ok, so what is missing now is a good IT for it. Disable the button on the server and enable it only on the client-side (by removing the `disabled` attribute), and then click on it. The server shouldn't execute any listeners.
</blockquote></details>

Yes, that is true, but with the current situation, i am not sure what is the correct implementation for the `setEnabled()` method, if it inherited from `hasEnabled`, as you know the `disabled` attribute is not adding to the component.  I am blocking this PR for now.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/50)*

**Comment by ZheSun88** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/50#-L9iH4q7AAAjpMEsn2qe:-L9jDywD7TB4B47q-di5:b-8dga0w) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

Yes, that is true, but with the current situation, i am not sure what is the correct implementation for the `setEnabled()` method, if it inherited from `hasEnabled`, as you know the `disabled` attribute is not adding to the component.  I am blocking this PR for now.
</blockquote></details>

Now, I have added an IT test, by removing `disabled` attribute and clicking from client again @gilberto-torrezan 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/50)*

**Comment by gilberto-torrezan** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/50#-:-L9jLxd14YCxrBxGnL3W:bnfp4nl)*

**Pull request merged**
