### PR TITLE
Update parent project to latest version

### PR DESCRIPTION
**Pull request by mstahv**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button-flow/97)

### CODE REVIEW

**Comment by mstahv** [comment]
So what should I do with that? That is not updated since last release? 🤔

**Comment by denis-anisimov** [comment]
Looks like there is no any need in `component-base` `1.3` version .

There should not be `1.3` `component-base` version at all.

**Comment by mstahv** [comment]
Now I’m not following at all, what should I do?

**Comment by denis-anisimov** [comment]
The question is why do you want to have `1.3` component-base here?
Based on that: 
- either just close this PR
- understand the need

**Comment by mstahv** [comment]
So we are not talking about the actual project version anymore?

I want the new parent because I want the features of the latest development version of the flow-project-page (and especially JDK 9+ compatibility coming, hopefully soon, via https://github.com/vaadin/flow-component-base/pull/113 ).

**Comment by denis-anisimov** [comment]
Aaaah.
Sorry , I have a mess in my head already. I don't remember all the things. Too many reviews, questions and so on.....

Now I recall the beginning of the story..

Could you please just make a fix into `flow-component-base`  using `1.2` branch directly instead of `master`?

That should suites your needs.

`1.3-snapshot` for `flow-component-base` is created for unknown reason. I cannot get a good answer why we have it at all. It's used in the `master`  branch of `Grid`  but I don't know reason why.

We have mess here as well since someone has created a new version and he doesn't remember the reason and he is almost not a team member.....

**Comment by mstahv** [comment]
So you mean https://github.com/vaadin/flow-component-base/pull/113 should go to a 1.2 branch? Then it would be forgotten when things progress 🤔 And 1.2 is released already. http://repo1.maven.org/maven2/com/vaadin/flow-component-base/

IIRC There was also some other components using 1.3-SNAPSHOT of flow-component-base too. All those would also then also be needed to be downgraded.

**Comment by denis-anisimov** [comment]
> So you mean [vaadin/flow-component-base#113](https://github.com/vaadin/flow-component-base/pull/113) should go to a 1.2 branch? Then it would be forgotten when things progress 🤔 And 1.2 is released already. http://repo1.maven.org/maven2/com/vaadin/flow-component-base/
> 

Yes.
We are releasing LTS 12 versions. So there will be `12.0.XXX` with those changes

vaadin/flow-component-base#113 should stay as is and it will be merged once it's possible.

Just make another PR for `1.2`  branch.

> IIRC There was also some other components using 1.3-SNAPSHOT of flow-component-base too. All those would also then also be needed to be downgraded.

I really have no any idea why we have `1.3` flow-component-base .
And also I don't understand why do we have `1.2`  branch for the `button`  e.g. if it's the same as `master`.

That makes a lot of confusion. I've asked about this in our channel but nobody cares.

The facts are:
- the `master` branch here is the same as `1.2`.
- as a side note: I don't know why we need `master`  branch identical to `1.2`
- branches should remain identical.
- if you increase base component version in the `master` then we will cherry-pick it for `1.2`  (see the item  above). This has no sense.

As a result: if you (for some reason) want `button`  in the master branch to be dependent on `1.3` flow-component-base then you should bump the `button` version as well to `1.3`

**Comment by pleku** [comment]
Not valid anymore, done as part of another PR

**Pull request closed without merging**
