### PR TITLE
Adding a more convenient Constructor for VaadinIcon

### PR DESCRIPTION
**Pull request by campbellbartlett**
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button-flow/112)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Thanks for your contribution but components should not depend on each other except cases when it's a part of their generically functionality.
Otherwise it may introduce circular dependencies and the existing functionality already allows to have what you want. It's not reasonable to have a constructor per every component which someone wants.

**Comment by campbellbartlett** [comment]
Ahh thats too bad, but you make some very strong points.
Thanks for taking the time to review.

**Comment by Legioth** [comment]
I think it would be acceptable to make `vaadin-button-flow` depend on `vaadin-icon-flow` since buttons are clearly on a higher level of abstraction than icons which means that there isn't a big risk of circular dependencies.

On the other hand, I do agree that it would be unfortunate if the API would depend specifically on the icon set represented by `VaadinIcon` while not offering the same shorthand alternatives for other icon sets.

To deal with this, I would suggest a two-phased approach where `vaadin-icon-flow` is first updated to have an interface such as `IconFactory` (I'm not sure about that exact name) which is implemented by `VaadinIcon` but can also be implemented by any other icon set (as long as it depends on `vaadin-icon-flow`). The `Button` constructors could then accept an instance of `IconFactory` instead of being tied to a specific icon set implementation.

**Comment by campbellbartlett** [comment]
Were you thinking of an interface something along the lines of:
```
public interface HasIconFactory{ 
    Icon create();
}
```
this way, the current implementation of Vaadin Icon already adheres to the interface?

**Comment by Legioth** [comment]
Yes, that was what I had in mind.

**Comment by campbellbartlett** [comment]
I've raised a PR against Vaadin-Icons-Flow with the suggested changes. Once that PR is merged, I'll reopen this one and push a new commit that makes use of the new interface.

**Comment by campbellbartlett** [comment]
Hi, now that [this](https://github.com/vaadin/vaadin-icons-flow/pull/45) PR is merged can we reopen this one?

**Comment by Legioth** [comment]
Since the actual solution will look slightly different now, I think it would be clearest if there would be a completely new PR instead of continuing on this one?

**Pull request closed without merging**
