### PR TITLE
Button should clear all nodes.

### PR DESCRIPTION
**Pull request by caalador**
When setting text to the button anything on
the client side should be removed also and
be replaced by the given text.

Note. this will pollute the demo with the test html file.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button-flow/53)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/main/webapp/frontend/template-button.html, line 13 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/53#-LAW_x3X-ovWkDrr4SYa:-LAW_x3X-ovWkDrr4SYb:b2sh3un) ([raw file](https://github.com/vaadin/vaadin-button-flow/blob/f2c5a639f59336644f5669b4096fa36c9b3a9824/src/main/webapp/frontend/template-button.html#L13)):*
> ```
> Template caption
> ```

May be it has also sense to add some inner non text elements here to check whether they are removed.

But I'm not sure whether they have sense for the button.

---

*[src/main/webapp/frontend/template-button.html, line 26 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/53#-LAWaCdn9iGbSXk1CNGn:-LAWaCdn9iGbSXk1CNGo:b-d0wxhj) ([raw file](https://github.com/vaadin/vaadin-button-flow/blob/f2c5a639f59336644f5669b4096fa36c9b3a9824/src/main/webapp/frontend/template-button.html#L26)):*
> ```HTML
>         customElements.define(TemplateButton.is, TemplateButton);
>     </script>
> </dom-module>
> ```

new line

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/53)*

**Comment by caalador** [comment]
Review status: 1 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[src/main/webapp/frontend/template-button.html, line 13 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/53#-LAW_x3X-ovWkDrr4SYa:-LAX5c9k1GXuz2sNSGY2:b-896fix) ([raw file](https://github.com/vaadin/vaadin-button-flow/blob/f2c5a639f59336644f5669b4096fa36c9b3a9824/src/main/webapp/frontend/template-button.html#L13)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> ```
> Template caption
> ```

May be it has also sense to add some inner non text elements here to check whether they are removed.

But I'm not sure whether they have sense for the button.
</blockquote></details>

Done.

---

*[src/main/webapp/frontend/template-button.html, line 26 at r1](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/53#-LAWaCdn9iGbSXk1CNGn:-LAX5cPy4FTPICNLQa8y:b-896fix) ([raw file](https://github.com/vaadin/vaadin-button-flow/blob/f2c5a639f59336644f5669b4096fa36c9b3a9824/src/main/webapp/frontend/template-button.html#L26)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

new line
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/53)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/53#-:-LAX9mpXDDHkYKTEy3MR:bnfp4nl)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/53)*

**Comment by denis-anisimov** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vaadin/vaadin-button-flow/53#-:-LAXAYsL734SfyyTb6X4:bnfp4nl)*

**Pull request merged**
