### PR TITLE
Add a new constructor for button usage

### PR DESCRIPTION
**Pull request by ZheSun88**
this constructor will allow user to add text, Icon and
clickeventListener in one method.

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button-flow/25)

### CODE REVIEW

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25#-KzcGQlrBdLQY-oIofoD:-KzcGQlrBdLQY-oIofoE:b4jws9n) (no related file):*
Would be good to extend existing unit test to test the new CTOR (check that icon and text are set).

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25#-KzcGQlrBdLQY-oIofoD:-KzcGphV7zayoXB6acSI:brvkoeg) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Would be good to extend existing unit test to test the new CTOR (check that icon and text are set).
</blockquote></details>

aha.. okay, working on that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25#-KzcGQlrBdLQY-oIofoD:-KzcZsV_JsnKUaEPPYYD:bhx3hr6) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

aha.. okay, working on that.
</blockquote></details>

@denis-anisimov  i just checked the unit test class we have,  we basic didn't check any class with `click listener`... and we have some unit checks for icon and text already... Can you give me some ideas

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25#-KzcGQlrBdLQY-oIofoD:-KzcbOEWi1iUJaAwG5AW:b8j027o) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

@denis-anisimov  i just checked the unit test class we have,  we basic didn't check any class with `click listener`... and we have some unit checks for icon and text already... Can you give me some ideas
</blockquote></details>

Yeah, I know. There are no tests for click listeners. It's too cumbersome.
Please ignore them.
But tests for `icon` and `text`  are easy ones. I meant only them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25#-KzcGQlrBdLQY-oIofoD:-Kzcc_69fKvUtVGOTuDz:bdd0saj) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Yeah, I know. There are no tests for click listeners. It's too cumbersome.
Please ignore them.
But tests for `icon` and `text`  are easy ones. I meant only them.
</blockquote></details>

if you mean only them,in the test file, i have found tests like this 
```
@Test
    public void textAndIconCtor() {
        Icon icon = new Icon();
        button = new Button("foo", icon);
        Assert.assertEquals("foo", button.getText());
        Assert.assertEquals(icon, button.getIcon());
    }
```
and some tests on icon and text individually... 

or you mean i should use the new constructor to test `icon` and `text`, like
```
@Test
    public void textIconAndEventCtor() {
        Icon icon = new Icon();
        button = new Button("foo", icon, event->null);
        Assert.assertEquals("foo", button.getText());
        Assert.assertEquals(icon, button.getIcon());
    }
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25#-KzcGQlrBdLQY-oIofoD:-KzdQtizmyreW3DQ3WHQ:bir404) (no related file):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

if you mean only them,in the test file, i have found tests like this 
```
@Test
    public void textAndIconCtor() {
        Icon icon = new Icon();
        button = new Button("foo", icon);
        Assert.assertEquals("foo", button.getText());
        Assert.assertEquals(icon, button.getIcon());
    }
```
and some tests on icon and text individually... 

or you mean i should use the new constructor to test `icon` and `text`, like
```
@Test
    public void textIconAndEventCtor() {
        Icon icon = new Icon();
        button = new Button("foo", icon, event->null);
        Assert.assertEquals("foo", button.getText());
        Assert.assertEquals(icon, button.getIcon());
    }
```
</blockquote></details>

You have added a new CTOR.
It would be good to be sure that no one else won't break it's behavior in the future.
So I'm asking to add the tests for the newly added CTOR.
It's about the last test in your comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25)*

**Comment by ZheSun88** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25#-KzcGQlrBdLQY-oIofoD:-KzgmeHp8T8xYroR3e5U:b-3vhec4) (no related file):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

You have added a new CTOR.
It would be good to be sure that no one else won't break it's behavior in the future.
So I'm asking to add the tests for the newly added CTOR.
It's about the last test in your comment.
</blockquote></details>

i have add a new unit test there... ;-).

btw, just found the readme file hasnt been updated, it comes in the same branch...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25)*

**Comment by denis-anisimov** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/ui/button/ButtonTest.java, line 71 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25#-KzgpG3M-JJW2QgowGZ_:-KzgpG3Ni-5VzedrqM3O:b1h0776) ([raw file](https://github.com/vaadin/vaadin-button-flow/blob/243737dad191346d491c70b0fe72f680dbaa6553/src/test/java/com/vaadin/ui/button/ButtonTest.java#L71)):*
> null

Better to replace with no-op here.
I would consider accepting `null` as a listener as a bug (out of the scope of this PR).
Once it's fixed this will be needed to be fixed as well.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25)*

**Comment by ZheSun88** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/ui/button/ButtonTest.java, line 71 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25#-KzgpG3M-JJW2QgowGZ_:-KzgzcYcKnQGJCINqkKT:bkih8nm) ([raw file](https://github.com/vaadin/vaadin-button-flow/blob/243737dad191346d491c70b0fe72f680dbaa6553/src/test/java/com/vaadin/ui/button/ButtonTest.java#L71)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> null

Better to replace with no-op here.
I would consider accepting `null` as a listener as a bug (out of the scope of this PR).
Once it's fixed this will be needed to be fixed as well.
</blockquote></details>

no-op here mean... should i use the `Ctor` in the way like .`new Button("foo", icon)`? or what would be the way for `no-op`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25)*

**Comment by denis-anisimov** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/ui/button/ButtonTest.java, line 71 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25#-KzgpG3M-JJW2QgowGZ_:-KzhKy9sLCMlXVqs1_xr:b8i5j7) ([raw file](https://github.com/vaadin/vaadin-button-flow/blob/243737dad191346d491c70b0fe72f680dbaa6553/src/test/java/com/vaadin/ui/button/ButtonTest.java#L71)):*
> new Button("foo", icon, null);

`new Button("foo", icon, event -> {});`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25)*

**Comment by ZheSun88** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/test/java/com/vaadin/ui/button/ButtonTest.java, line 71 at r2](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25#-KzgpG3M-JJW2QgowGZ_:-KzhftfkgWRI3RifS_zM:b-3ugqak) ([raw file](https://github.com/vaadin/vaadin-button-flow/blob/243737dad191346d491c70b0fe72f680dbaa6553/src/test/java/com/vaadin/ui/button/ButtonTest.java#L71)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

> new Button("foo", icon, null);

`new Button("foo", icon, event -> {});`
</blockquote></details>

Thanks Denis.. done!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25)*

**Comment by denis-anisimov** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/25)*

**Pull request merged**
