### PR TITLE
Rename package com.vaadin.ui to com.vaadin.flow.component

### PR DESCRIPTION
**Pull request by denis-anisimov**
Part of package renaming #3032

---
This change is [Reviewable](https://reviewable.io/reviews/vaadin/vaadin-button-flow/31)

### CODE REVIEW

**Comment by caalador** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/button/Button.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/31#-L0KSnCrvEo87WJxnzlf:-L0KSnCrvEo87WJxnzlg:b-gssynr) ([raw file](https://github.com/vaadin/vaadin-button-flow/blob/956c744908e9437979cce107a125199876d38e0b/src/main/java/com/vaadin/flow/component/button/Button.java#L23)):*
> ```Java
> import com.vaadin.flow.dom.ElementFactory;
> import com.vaadin.ui.Component;
> import com.vaadin.ui.button.GeneratedVaadinButton;
> ```

This import should be com.vaadin.flow.component.button.GeneratedVaadinButton

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/31)*

**Comment by ZheSun88** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/button/Button.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/31#-L0KSnCrvEo87WJxnzlf:-L0OTI78m-7FMVAhsyxx:b-hrf7yo) ([raw file](https://github.com/vaadin/vaadin-button-flow/blob/956c744908e9437979cce107a125199876d38e0b/src/main/java/com/vaadin/flow/component/button/Button.java#L23)):*
<details><summary><i>Previously, caalador wrote…</i></summary><blockquote>

This import should be com.vaadin.flow.component.button.GeneratedVaadinButton
</blockquote></details>

@denis-anisimov remember to solve this...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/31)*

**Comment by denis-anisimov** [comment]
Review status: 0 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/main/java/com/vaadin/flow/component/button/Button.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/31#-L0KSnCrvEo87WJxnzlf:-L0OZhuCP136LXPaeeZG:b-896fix) ([raw file](https://github.com/vaadin/vaadin-button-flow/blob/956c744908e9437979cce107a125199876d38e0b/src/main/java/com/vaadin/flow/component/button/Button.java#L23)):*
<details><summary><i>Previously, ZheSun88 (Sun Zhe) wrote…</i></summary><blockquote>

@denis-anisimov remember to solve this...
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/31)*

**Comment by caalador** [comment]
Reviewed 1 of 10 files at r1, 1 of 2 files at r2.
Review status: 1 of 5 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[src/main/java/com/vaadin/flow/component/button/Button.java, line 23 at r1](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/31#-L0KSnCrvEo87WJxnzlf:-L0O_Hgp67MjiW5J628b:b-6flpf3) ([raw file](https://github.com/vaadin/vaadin-button-flow/blob/956c744908e9437979cce107a125199876d38e0b/src/main/java/com/vaadin/flow/component/button/Button.java#L23)):*
<details><summary><i>Previously, denis-anisimov (Denis) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You fixed ButtonView, but this is in Button.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/31)*

**Comment by ZheSun88** [comment]
Reviewed 8 of 10 files at r1, 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vaadin/vaadin-button-flow/31)*

**Pull request merged**
